@extends('eng.alabio')
@section('meta')
    <title>Terminos y Condiciones</title>
@endsection
@section('style-product')
  <link rel="stylesheet" type="text/css" href="{{ asset('css/pages.css') }}">
@endsection

@section('content')
	<div class="present">
        <div class="text-present">
          <h2>Terminos y Condiciones</h2>
            <a href="{{ url('/') }}">inicio</a><b> / Terminos y Condiciones</b>
         </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
        <p align="justify"><b>1) Aceptación:</b> Nosotros aceptamos y confirmamos su orden de productos descritos en el contrato o la factura proveída a usted al momento de su orden. Usted acepta los términos y condiciones de la venta escrita en esta página. Ningunos términos adicionales son aceptables para Alabio Toys. Al menos acordados en un escrito firmado por Alabio Toys. Estos términos y condiciones son exclusivos y respaldan todos los otros términos y condiciones que aparezcan en la factura del comprador o donde quiera y aplica a todas las referencias hechas y ordenes aceptadas por Alabio Toys. Al menos escrito especialmente a lo contrario en el frente de la confirmación de la orden. Es la responsabilidad del comprador verificar con los gobiernos locales acerca de cualquier ley y regulación relacionada con la compra y uso de los productos. Alabio Toys no es responsable por cualquier error escrito en alguna cláusula, órdenes o publicaciones.</p>
        <p align="justify"><b>2) Pagos: Pagos se harán de la siguiente forma:</b> El comprador tiene que dar 50% de depósito sin devolución en el precio de cada producto hecho en especial y que no esté en nuestro inventario. El balance tiene que ser pagable dentro de 48 horas de la fecha de envío del producto. La fecha cierre es proveída por Alabio Toys en la factura proveída al comprador al momento de tomar la orden. Ordenes sin pagos iniciales no serán hechas en producción. La fecha de envío escrita en la hoja de confirmación de venta reflejara el pago inicial recibido, consecuentemente días adicionales podrían ser añadidos a la fecha de envío por cada día que el pago inicial no se haya recibido. Para órdenes de equipo o productos en nuestro inventario, se requiere 100% del pago. Para compras pagadas con tarjetas de crédito o débito realizadas en nuestra tienda en linea, el comprador deberá pagar el 100% del valor del producto. Todas las transacciones deberán de ser en pesos mexicanos en forma de efectivo, transferencia electrónica, depósito bancario, o tarjeta de crédito o débito.</p>
        <p align="justify"><b>3) Cancelación:</b> Todas las ventas son finales. Las órdenes pueden ser canceladas sin costo alguno si la cancelación se hace dentro de 24 horas de la fecha de la factura solamente siempre y cuando la producción de su producto no haya comenzado. Cancelaciones hechas después de la fecha de la factura resultaran en un 25% por gastos de almacenamiento, con la excepción de órdenes especiales que tienen un cargo de 50% por gastos de almacenamiento.</p>
        <p align="justify"><b>4) Envíos:</b> Al menos que el comprador lo requiera, Alabio Toys usara a su discreción su compañía preferida de envíos para enviar los productos al comprador. Los productos serán enviados desde la compañía Alabio Toys en cualquiera de sus sucursales en la Matriz en Puebla, Pue; Querétaro, Qro. Amenos que este escrito en la factura, todos los costos y gastos relacionados al envío, incluyendo aseguranza, aduanas, impuestos, etc. es y será la responsabilidad del comprador. El comprador tiene que inspeccionar los paquetes por daños antes de firmar la hoja de entrega. El comprador no debe aceptar el envío si hay daños visibles en los paquetes o debería hacer una nota en la hoja de entrega, para evaluación de reclamo. Cualquier reclamo de envío tiene que ser hecho inmediatamente a la compañía de envíos. Todos los costos de envío hacia o desde nuestra fábrica para reparar o remplazar productos con garantía será responsabilidad del comprador. Alabio Toys no se hace responsable de la pérdida o daño de los productos que sean responsabilidad directa de la empresa de carga.</p>
        <p align="justify"><b>5) Garantía Limitada:</b> Alabio Toys provee al comprador garantía de reparación limitada o remplazo y acuerda y garantiza la garantía de los productos, los cuales serán usados para el propósito destinado, mercantil, y sin defectos de construcción y materiales por el periodo y tipos de productos especificados en la categoría de abajo. a) Todos los brincolines inflables vienen con dos (2) años de garantía desde la fecha de compra. b) Todas las resbaladillas o juegos interactivos que usan agua vienen con 2 años de garantía desde la fecha de compra. c) Todos juegos Arcades, Mesas de Juego o Futbolitos vendidos para uso adentro de edificios vienen con 1 año de garantía desde la fecha de compra. d) Ninguna garantía es extendida por otros equipos no hechos por Alabio Toys, y todo reclamo de garantía tiene que ser con la compañía que hizo el equipo e) Garantía sobre motores es de 1 año. Mal uso, forma inadecuada de usarlo o guardarlo, mantenimiento inadecuado, abuso o tratamiento negligente del producto hará inválida la cobertura de garantía de Alabio Toys. Color: Un producto no será considerado defectivo si el color difiere de nuestro catálogo, pagina web, factura del comprador o cualquier forma de publicidad. Ninguna garantía es ofrecida con relación a color. Colores y diseño gráfico pueden cambiar sin nota previa y no serán considerados defectos. Tolerancias: Todas las dimensiones escritas en el catálogo de Alabio Toys, pagina web, factura del comprador o cualquier forma de publicidad o algún otro medio que pertenezcan a los productos vendidos por Alabio Toys son aproximaciones y dentro de tolerancias de la industria. Ninguna garantía es ofrecida con relación a las medidas exactas del producto. Peso: Todos los pesos escritos en el catálogo de Alabio Toys, pagina web, factura del comprador o cualquier forma de publicidad o algún otro medio que pertenezcan a los productos vendidos son aproximaciones y dentro de tolerancias de la industria. Ninguna garantía es ofrecida con relación a pesos exactos del producto. Todos los pedidos del comprador para trabajo de garantía o reemplazos están sujetos a inspección en la fábrica de Alabio Toys. Evaluación final de reclamo de garantía se hará cuando el producto llegue a la fábrica de Alabio Toys. Una foto o fotos del área afectada que requiera reparación son requeridas para presentar un reclamo. Trabajo de reparación con garantía será proveído por Alabio Toys. La garantía será anulada si cualquier modificación o reparación fueron hechas en una planta de reparación no autorizada. </p>
        <p align="justify"><b>6) Inspección:</b> El comprador deberá inspeccionar los productos el mismo día que los reciba y deberá notificar a Alabio Toys por escrito cualquier reclamo, dentro de tres (3) días de trabajo, usando carta certificada, después que el comprador descubre evidencia y base de su reclamo. Falla del comprador de proveer nota escrita para un reclamo dentro del tiempo periodo de inspección hará nulo su reclamo por productos defectuosos y concluirá como prueba que el comprador recibió los productos sin ningún defecto. </p>
        <p align="justify"><b>7) Impuestos:</b> Todos las ventas están sujetas a federal, estado o impuestos locales, si algún, pertinente al lugar de entrega. El comprador deberá pagar impuestos en la orden, y todos las penalidades e interés, si algún, adquirido. </p>
        <p align="justify"><b>8) Renuncia:</b> Las provisiones en el párrafo 5 son la única obligación de Alabio Toys. No somos responsables si el comprador o cualquier otra persona se lastiman o por daños o pérdidas de propiedad o valor causado por cualquier producto que haya sido sujeto a mal uso, negligencia, o accidente. O uso indebido: O modificado o reparado por personas no autorizadas: o instalado inadecuadamente y sin manteniendo apropiado. </p>
        <p align="justify"><b>9) Uso e Indemnización:</b> El Comprador (persona, compañía o entidad que compra los productos inflables), es responsable de la manera del uso de los productos y equipos comprados de Alabio Toys. Del Comprador es responsabilidad todos los rótulos, etiquetas, y avisos al consumidor u otros usuarios de los productos y equipo, y o cualquier otro acto necesario, incluyendo avisos al usuario y limitaciones tales como (peso, altura, edad, número de participantes, y limitaciones de condiciones de salud), para asegurar la seguridad de los usuarios. El Comprador hace constar que recibieron, leyeron y entendieron correctamente todo las instrucciones necesarias para la seguridad de instalación y operación de su producto inflable o aparato. "Comprador" está de acuerdo en operar su producto inflable o aparato de acuerdo a las instrucciones establecidas por Alabio Toys. "Comprador" está de acuerdo en operar su producto inflable o aparato de acuerdo a los requerimientos del estado o local. "Comprador" está de acuerdo en llevar aseguranza en conexión con el uso del "Comprador" o renta de cualquier producto comprado de Alabio Toys. "Comprador" está de acuerdo en entrenar cualquier persona que opera los productos inflables o aparatos en forma segura de operación de los productos inflables o aparatos incluyendo forma segura en situaciones de emergencia. "Comprador" deberá usar estacas, cuerda de amarre, y otros dispositivos necesarios para asegurar la seguridad de los usuarios y el público en general. "Comprador" se compromete a indemnizar, defender sin perjudicar a Alabio Toys y los aseguradores de Alabio Toys de cualquier acción o demanda de terceras personas, incluyendo compradores y usuarios de los productos vendidos al "Comprador", que se origine o en conexión con el uso de los productos descritos o resultados de violación a las prohibiciones en esta Confirmación de Orden del Comprador. En el evento que Alabio Toys es requerido a comenzar una acción para esforzar esta prohibición, Comprador deberá pagar a Alabio Toys todos los costos y gastos legales.</p>
            
    </div>
@endsection